# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '横屏测试' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 横屏测试


pod 'JPNavigationController', '~> 2.0.1'
pod 'JRSwizzle'

end
