# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZQLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZQLive
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.1.2'
pod 'Masonry', '~> 1.1.0'
pod 'YYKit', '~> 1.0.9'
end
