# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XMPPTtest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XMPPTtest

use_frameworks!
pod 'XMPPFramework', '~> 3.7.0'

end
