# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cell的高度自动计算的三方开源库' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cell的高度自动计算的三方开源库

pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
pod 'Masonry', '~> 1.1.0'

end
