# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sqlite_test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sqlite_test

pod 'Masonry', '~> 1.1.0'

end
