# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xmpp测试' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xmpp测试

use_frameworks!
# 3.7 Stable Release
pod 'XMPPFramework', '~> 3.7.0'

end
