# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_practice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IOS_practice

  target 'IOS_practiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS_practiceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

	pod 'Masonry', '~> 1.1.0'

end
